update to fedora 42 with proper layer committing

diff --git a/desktop/sway/Containerfile b/desktop/sway/Containerfile
--- a/desktop/sway/Containerfile
+++ b/desktop/sway/Containerfile
@@ -1,31 +1,28 @@
-FROM quay.io/fedora-ostree-desktops/sway-atomic:41
+FROM quay.io/fedora-ostree-desktops/sway-atomic:42
 
 # dnf configuration has to be in effect during build
 COPY desktop/sway/etc/dnf /etc/dnf
 
 # Add rpmfusion repositories
-RUN dnf5 -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
-                    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
-    # dnf5 -y group upgrade core
+RUN <<EOF 
 
-# Install ffmpeg (removing all the -free replacements is required) and openh264
-RUN dnf5 -y install --allowerasing ffmpeg && \
-    dnf5 -y group install multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin && \
-    dnf5 -y group install sound-and-video && \
-    dnf5 -y swap noopenh264 openh264 && \
-    dnf5 -y install mozilla-openh264
-
-# Install Hardware Accelerated Codecs for AMD GPUs. This improves video playback and encoding performance on systems with AMD graphics.
-RUN dnf5 -y swap mesa-va-drivers mesa-va-drivers-freeworld && \
-    dnf5 -y swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld
-
-# Bulk of layered packages
-RUN dnf5 -y install \
+  set -xeuo pipefail
+  dnf5 -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
+  dnf5 -y install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
+  dnf5 -y install --allowerasing ffmpeg
+  dnf5 -y group install multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
+  dnf5 -y group install sound-and-video
+  dnf5 -y swap noopenh264 openh264
+  dnf5 -y install mozilla-openh264
+  dnf5 -y swap mesa-va-drivers mesa-va-drivers-freeworld
+  dnf5 -y swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld
+  dnf5 -y install \
       android-tools \
       vim \
       bat \
       btop \
       pv \
+      fzf \
       zstd \
       nmap-ncat \
       distrobox \
@@ -40,14 +37,11 @@ RUN dnf5 -y install \
       tlp \
       tlp-rdw
 
-
-# Failed to resolve the transaction:
-# Problem: conflicting requests
-#   - package rocm-opencl-6.2.1-2.fc41.x86_64 from updates-archive requires ocl-icd(x86-64), but none of the providers can be installed
-RUN dnf5 -y swap OpenCL-ICD-Loader ocl-icd
-
-
-RUN dnf5 -y install \
+  # Failed to resolve the transaction:
+  # Problem: conflicting requests
+  #   - package rocm-opencl-6.2.1-2.fc41.x86_64 from updates-archive requires ocl-icd(x86-64), but none of the providers can be installed
+  dnf5 -y swap OpenCL-ICD-Loader ocl-icd
+  dnf5 -y install \
       rocminfo \
       rocm-opencl \
       rocm-clinfo \
@@ -55,37 +49,46 @@ RUN dnf5 -y install \
       rocm-hip \
       --allowerasing
 
-# Set vim as default editor
-RUN dnf5 -y swap nano-default-editor vim-default-editor
+  dnf5 -y swap nano-default-editor vim-default-editor
+  # Install virtualization tools
+  dnf5 -y group install virtualization
 
-# Install virtualization tools
-RUN dnf5 -y group install virtualization
+  # Remove Firefox rpm (superseded by flatpak Firefox)
+  rpm -e firefox firefox-langpacks
 
-# Remove Firefox rpm (superseded by flatpak Firefox)
-RUN rpm -e firefox firefox-langpacks
+  # Remove unneeded packages (currently doesn't actually reduce space, but reduces clutter)
+  dnf5 -y autoremove
 
-# Remove unneeded packages (currently doesn't actually reduce space, but reduces clutter)
-RUN dnf5 -y autoremove
+  ostree container commit
+EOF
 
 # Apply configuration
 COPY desktop/sway/etc /etc
 COPY desktop/sway/usr /usr
 
-# Apply hardened firewall configuration
-# RUN firewall-offline-cmd --set-default-zone public
-RUN firewall-offline-cmd --remove-service ssh
+RUN <<EOF 
+  # Apply hardened firewall configuration
+  # RUN firewall-offline-cmd --set-default-zone public
+  firewall-offline-cmd --remove-service ssh
 
-RUN systemctl enable tailscaled.service
+  systemctl enable tailscaled.service
 
-# Power management
-RUN systemctl enable tlp
-RUN systemctl mask systemd-rfkill.service systemd-rfkill.socket
+  # Power management
+  systemctl enable tlp
+  systemctl mask systemd-rfkill.service systemd-rfkill.socket
 
-RUN systemctl enable podman-auto-update.service podman-auto-update.timer
-RUN systemctl enable podman-auto-update.service podman-auto-update.timer
+  systemctl enable podman-auto-update.service podman-auto-update.timer
+  systemctl enable podman-auto-update.service podman-auto-update.timer
 
-# Restrict permissions on quadlet directory
-RUN chmod 700 /etc/containers/systemd
+  # Restrict permissions on quadlet directory
+  chmod 700 /etc/containers/systemd
+  ostree container commit
+EOF
 
-# https://github.com/ostreedev/ostree-rs-ext/issues/159
-RUN ostree container commit
+
+RUN bootc container lint
+
+LABEL containers.bootc="1" \
+      ostree.bootable="1"
+STOPSIGNAL SIGRTMIN+3
+CMD ["/sbin/init"]
